### ISSUE TITLE
Nodule malignancy prediction from CT scan

### ISSUE THREAD

**Issue by luantunez** [wentaozhu/DeepLung#128]
Thank you for sharing your model! 
With it, I would like to get a prediction on the nodules malignancy on a CT scan by using your pretrained models. 
For the detection stage I am using the 064.ckpt checkpoint as my pretrained model, I wonder if this is accurate or if I should use one of the checkpoints in the detector/resmodel folder (if so, which one?). 
On the other hand, I am having issues with the classification stage. Should I run it by using the main_nodcls.py file in the nodcls folder? Can I do so without an annotation.csv file? Because I would like to only use the detected nodules obtained in the previous stage with the CT scan. In this case, I would like to know which pretrained model to use for this classification stage. I have read in other issues that, in order to use the dpn3d.py model, I should use the checkpoints in the detector/dpnmodel folder. Though there are several checkpoint here, which one should I use to obtain a, accurate classification of the nodules on my CT scan?
I would like to clarify that I will be using any mhd/raw CT scan, not necessarily from the LUNA16 dataset. 
As the last question I would like to know why have you stored so many checkpoints in the resmodel and dpnmodel folders? What is the purpose of each of them and which ones are the final ones for obtaining accurate detection and classification results.
Thank you in advance!

**Comment by wentaozhu** [comment]
1 For the detection stage I am using the 064.ckpt checkpoint as my pretrained model, I wonder if this is accurate or if I should use one of the checkpoints in the detector/resmodel folder (if so, which one?).
064.ckpt is the initialization. Please use checkpoints in the detector/resmodel

2 I did not share the pretrained classification model in the repository.

3 Yes. Because of 10 fold cross validation, we have 10 models for each test set. You can try some models there.

4 It is the standard cross validation procedure. We validate which model if the best for the specific test set.

Thank you so much!

**Comment by luantunez** [comment]
﻿Thank you very much for your answer professor. I just have two follow up questions: 

1. What is the difference between the checkpoints in the resmodel folder and the ones in the dpnmodel folder? (If it is a group for classification and the other one for detection, which is which?)

2. Would it be possible for you to share the classification pretrained model? 

Thank you very much in advance and I apologize for the disturbance.

Lucía Antúnez

**Comment by wentaozhu** [comment]
1 There are both detection models. You can use resmodel. You can read "Deeplung: Deep 3d dual path nets for automated pulmonary nodule detection and classification, WACV 2018" https://arxiv.org/pdf/1801.09555.pdf to get to know the details.

2 The project is conducted two or three years ago. I do not have these models.

Thank you so much!
