### ISSUE TITLE
main_nodcls.py preprocesspath path?

### ISSUE THREAD

**Issue by blakeliu** [wentaozhu/DeepLung#2]
How can create preprocesspath = '/media/data1/wentao/tianchi/luna16/cls/crop_v3/' datasets?

**Comment by wentaozhu** [comment]
After preprocessing, we convert the CT slices into a 3D numpy array and get the new nodule annotations with posfix '_label.npy'. The nodule annotations are the center of the nodule and diameter of the nodule. You can use it to crop the nodule from the preprocessed 3D numpy array for nodule classification task. 

For nodule classification based on detection, remember to only use the true positive nodules because there are too many false positives if we want to keep as many nodules as possible.

**Comment by hsinming** [comment]
@blakeliu 
You can use the commented code in https://github.com/wentaozhu/DeepLung/blob/master/nodcls/data/nodclsgbt.py
to obtain the cropped "{srsid}.npy" in crop_v3 folder.

**Comment by wentaozhu** [comment]
The doctor's annotation is in ./nodcls/annotationdetclssgm_doctor.csv
