### ISSUE TITLE
tofrocwrtdetpepchluna16. Py

### ISSUE THREAD

**Issue by anruoxi123** [wentaozhu/DeepLung#40]
Hello, I am now to complete the training and test of the model, the next step to run. / evaluationScript frocwrtdetpepchluna16. py files, before running the file, need to do some what data processing, now I change the path to the project contained in the CSV path, will be submitted to the following error, this file is need to generate its own excuse me?
![7f06f02cff0f443957bb3f3b28863c0](https://user-images.githubusercontent.com/43407427/46990630-d3fedd00-d134-11e8-9343-92b0a53c50fd.png)
Thanks for comment！

**Comment by anruoxi123** [comment]
I looked at the val1 and other val folders generated by the test, which do not have.csv files.

**Comment by wentaozhu** [comment]
Line 144 DeepLung/evaluationScript/frocwrtdetpepchluna16.py uncomment

**Comment by anruoxi123** [comment]
Hello, according to your suggestion, I have cancelled the annotation of 144 lines, and the program can run part of it, but in the end, the error of CSV file cannot be found, please kindly advise where the problem is.

![0z 6_p o4r jw4lvb ii9x](https://user-images.githubusercontent.com/43407427/47064462-2b26af80-d212-11e8-8280-8789f1aad60f.png)

**Comment by wentaozhu** [comment]
Oh. I see. The final csv is constructed by concatenating the generated csv from each fold. Now, I think you are using 9 folds and validate 1 fold which is cross-validation. So you need to construct the csv for the validated fold. Do not use all the nodules of the 10 folds to calculate the FROC when you are calculating FROC for the current validated fold.

**Comment by wentaozhu** [comment]
Congratulations!

I think so. If not, you can try main_nodcls.py

Yes, LIDC-IDRI. Yes, first extract nodule in DeepLung/nodcls/data/

Take a look at code and issues in https://github.com/uci-cbcl/DeepLung.git 

Maybe there are some updates. Thank you very much for your interest!

**Comment by anruoxi123** [comment]
Ok, thank you very much!

**Comment by tan416tan** [comment]
I have same question，I run the tofrocwrtdetpepchluna16. Py can't get csv file ,i want know how to concatenate the generated csv from each fold?

**Comment by wentaozhu** [comment]
After you get the csv for each fold, you can concatenate them together for the final csv. Please read readme and find an example concatenated csv.
发自网易邮箱大师
On 10/24/2019 21:10, tan416tan wrote: I have same question，I run the tofrocwrtdetpepchluna16. Py can't get csv file ,i want know how to concatenate the generated csv from each fold?

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/wentaozhu/DeepLung/issues/40?email_source=notifications\u0026email_token=ACMYWLNIKGBJ4QWNIW7UKZ3QQGND7A5CNFSM4F3WACZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECE63RQ#issuecomment-545910214",
"url": "https://github.com/wentaozhu/DeepLung/issues/40?email_source=notifications\u0026email_token=ACMYWLNIKGBJ4QWNIW7UKZ3QQGND7A5CNFSM4F3WACZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECE63RQ#issuecomment-545910214",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
