### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by starwewe** [wentaozhu/DeepLung#94]
if I only have Luna dataset,can I train the model by using your code ?if ok,please tell me how I should do.Thank you

**Comment by wentaozhu** [comment]
Yes. Please refer to https://github.com/wentaozhu/DeepLung/blob/master/README.md

**Comment by wentaozhu** [comment]
Yes. Th detection is based on LUNA16. Please refer to readme.
发自网易邮箱大师
On 10/21/2019 09:53, Luckylu wrote: if I only have Luna dataset,can I train the model by using your code ?if ok,please tell me how I should do.Thank you

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/wentaozhu/DeepLung/issues/94?email_source=notifications\u0026email_token=ACMYWLKJDHDQYAJMMCZGLVDQPUDRXA5CNFSM4JCXETNKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HTBH77A",
"url": "https://github.com/wentaozhu/DeepLung/issues/94?email_source=notifications\u0026email_token=ACMYWLKJDHDQYAJMMCZGLVDQPUDRXA5CNFSM4JCXETNKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HTBH77A",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
